version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install libicu-dev
      - run: sudo docker-php-ext-install intl
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: ./vendor/bin/phpunit
      - store_test_results:
          path: ./test_results
