version: 2
jobs:
  build:
    docker:
      - image: newridetech/php:7e56d470f2a747579ef2a05db3b366cd815c3b79
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: ./vendor/bin/phpunit
      - store_test_results:
          path: ./test_results
